import { StyleSheet } from 'react-native';
import {
  borderWidth,
  colors,
  degree,
  elevation,
  opacity,
  radius,
  sizes,
  spacing,
  tokens,
  zIndex,
} from '../theme';

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: tokens.colorBgOverlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  modalBox: {
    width: '100%',
    maxWidth: sizes.modalMaxWidth,
    height: sizes.modalHeight,
    maxHeight: '92%',
    backgroundColor: colors.bgDark,
    borderWidth: borderWidth.md,
    borderColor: colors.surfaceBorder,
    borderRadius: radius.lg,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.lg,
    shadowColor: colors.shadowDark,
    shadowOpacity: opacity.shadowStrong,
    shadowRadius: 0,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: elevation.lg,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: spacing.lg,
    right: spacing.lg,
    width: sizes.closeButton,
    height: sizes.closeButton,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: zIndex.base,
  },
  closeButtonText: {
    color: colors.textSecondary,
    fontSize: tokens.fontSize3xl,
    lineHeight: tokens.lineHeight2xl,
    fontWeight: tokens.fontWeightLight,
    textTransform: 'uppercase',
  },
  illustration: {
    height: sizes.illustration,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  heart: {
    position: 'absolute',
    top: spacing.sm,
    color: colors.error,
    fontSize: tokens.fontSize5xl,
    lineHeight: tokens.lineHeight5xl,
    fontWeight: tokens.fontWeightBlack,
    textShadowColor: colors.shadowDark,
    textShadowOffset: {
      width: 0,
      height: 3,
    },
    textShadowRadius: 0,
  },
  star: {
    position: 'absolute',
    color: colors.primary,
    fontSize: tokens.fontSize2xl,
    lineHeight: tokens.lineHeightLg,
    fontWeight: tokens.fontWeightBlack,
    textShadowColor: colors.shadowDark,
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  starLeftTop: {
    top: 74,
    left: 58,
  },
  starLeftBottom: {
    bottom: 30,
    left: 74,
  },
  starRightTop: {
    top: 78,
    right: 62,
  },
  starRightBottom: {
    bottom: 54,
    right: 72,
  },
  planet: {
    width: sizes.planet,
    height: sizes.planet,
    marginTop: spacing.xl,
    overflow: 'hidden',
    borderRadius: sizes.modalHeight - sizes.modalMaxWidth,
    backgroundColor: tokens.cityButton,
    borderWidth: borderWidth.lg,
    borderColor: colors.shadowDark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  land: {
    position: 'absolute',
    backgroundColor: colors.success,
    borderColor: colors.shadowDark,
    borderWidth: borderWidth.sm,
  },
  landTopLeft: {
    top: 18,
    left: 16,
    width: 50,
    height: 38,
    borderRadius: radius.lg,
    transform: [{ rotate: degree.md }],
  },
  landTopRight: {
    top: 34,
    right: 16,
    width: 48,
    height: 44,
    borderRadius: radius.lg,
    transform: [{ rotate: `-${degree.xl}` }],
  },
  landBottomLeft: {
    bottom: 18,
    left: 20,
    width: 54,
    height: 38,
    borderRadius: radius.lg,
    transform: [{ rotate: degree.lg }],
  },
  landBottomRight: {
    right: 20,
    bottom: 24,
    width: 46,
    height: 54,
    borderRadius: radius.lg,
    transform: [{ rotate: degree.sm }],
  },
  eyeLeft: {
    position: 'absolute',
    top: 76,
    left: 51,
    width: 12,
    height: 18,
    borderRadius: radius.sm,
    backgroundColor: colors.shadowDark,
  },
  eyeRight: {
    position: 'absolute',
    top: 76,
    right: 51,
    width: 12,
    height: 18,
    borderRadius: radius.sm,
    backgroundColor: colors.shadowDark,
  },
  smile: {
    marginTop: spacing.xl,
    color: colors.shadowDark,
    fontSize: tokens.fontSize4xl,
    lineHeight: tokens.lineHeight3xl,
    fontWeight: tokens.fontWeightBlack,
  },
  title: {
    color: colors.primary,
    fontSize: tokens.fontSizeXl,
    fontWeight: tokens.fontWeightBlack,
    textAlign: 'center',
    marginBottom: spacing.md,
    textTransform: 'uppercase',
    textShadowColor: colors.shadowDark,
    textShadowOffset: {
      width: 0,
      height: 3,
    },
    textShadowRadius: 0,
  },
  text: {
    color: colors.textPrimary,
    fontSize: tokens.fontSizeMd,
    fontWeight: tokens.fontWeightBold,
    textAlign: 'center',
    marginBottom: spacing.lg,
    lineHeight: tokens.lineHeightMd,
    textShadowColor: colors.shadowDark,
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 0,
  },
  stepIndicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.md,
    marginBottom: spacing.xl,
  },
  stepDot: {
    width: sizes.dot,
    height: sizes.dot,
    borderRadius: radius.sm,
    backgroundColor: colors.textMuted,
    borderWidth: borderWidth.sm,
    borderColor: colors.surface,
  },
  stepDotActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primaryDark,
  },
  buttonContainer: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: spacing.md,
  },
  backButton: {
    flex: 1,
    minHeight: sizes.buttonMinHeight,
    backgroundColor: colors.surfaceLight,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.md,
    borderWidth: borderWidth.md,
    borderColor: colors.surfaceBorder,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    color: colors.textPrimary,
    fontSize: tokens.fontSizeSm,
    fontWeight: tokens.fontWeightBlack,
    textTransform: 'uppercase',
  },
  primaryButton: {
    flex: 1,
  },
});

export default styles;
