import { StyleSheet } from 'react-native';
import {
  borderWidth,
  colors,
  elevation,
  opacity,
  radius,
  sizes,
  spacing,
  typography,
} from '../theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgDark,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  backButtonWrapper: {
    width: sizes.closeButton,
    height: sizes.closeButton,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButton: {
    width: sizes.closeButton,
    height: sizes.closeButton,
    paddingVertical: 0,
    paddingHorizontal: 0,
    minHeight: 0,
    borderRadius: radius.sm,
    backgroundColor: colors.surfaceLight,
    borderWidth: borderWidth.sm,
    borderColor: colors.surfaceBorder,
    shadowOpacity: 0,
    shadowColor: 'transparent',
    shadowRadius: 0,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    elevation: 0,
  },
  backButtonLabel: {
    color: colors.textPrimary,
    fontSize: typography.fontSize.sm,
    letterSpacing: 1,
  },
  backButtonIcon: {
    position: 'absolute',
  },
  headerSpacer: {
    width: sizes.closeButton + spacing.xs,
    height: sizes.closeButton + spacing.xs,
  },
  title: {
    flex: 1,
    paddingHorizontal: spacing.sm,
    textAlign: 'center',
    color: colors.primary,
    fontSize: typography.fontSize.lg,
    fontWeight: typography.fontWeight.black,
    textTransform: 'uppercase',
    letterSpacing: 1,
    textShadowColor: colors.shadowDark,
    textShadowOffset: {
      width: 0,
      height: 3,
    },
    textShadowRadius: 0,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: borderWidth.md,
    borderColor: colors.surfaceBorder,
    paddingHorizontal: spacing.md,
    shadowColor: colors.shadowDark,
    shadowOpacity: opacity.shadowStrong,
    shadowRadius: 0,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    elevation: elevation.md,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.md,
    borderBottomWidth: borderWidth.sm,
    borderBottomColor: colors.surfaceBorder,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  rowRight: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: spacing.sm,
  },
  iconBadge: {
    width: sizes.closeButton,
    height: sizes.closeButton,
    borderRadius: radius.sm,
    backgroundColor: colors.surfaceLight,
    borderWidth: borderWidth.sm,
    borderColor: colors.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowLabel: {
    flexShrink: 1,
    color: colors.textPrimary,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.black,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  rowLabelDestructive: {
    flexShrink: 1,
    color: colors.error,
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.black,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  languageRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  languageText: {
    color: colors.textSecondary,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    textTransform: 'capitalize',
  },
});

export default styles;
